### ISSUE TITLE
pip install mergem successfully but I cannot import

### ISSUE THREAD

**Issue by luwenyi111** [lobolab/mergem#7]
(py37) winnie@LAPTOP-BPTISFKJ:/mnt$ mergem --version
Traceback (most recent call last):
  File "/home/winnie/anaconda3/envs/py37/bin/mergem", line 5, in <module>
    from mergem.cli import main
  File "/home/winnie/anaconda3/envs/py37/lib/python3.7/site-packages/mergem/__init__.py", line 2, in <module>
    from .__merge_models import merge, translate
  File "/home/winnie/anaconda3/envs/py37/lib/python3.7/site-packages/mergem/__merge_models.py", line 280
    if (idx := alt_old_met_id.rfind('@')) > 0 or (idx := alt_old_met_id.rfind('_')) > 0:
            ^

(py37) winnie@LAPTOP-BPTISFKJ:/mnt$ mergem --help
Traceback (most recent call last):
  File "/home/winnie/anaconda3/envs/py37/bin/mergem", line 5, in <module>
    from mergem.cli import main
  File "/home/winnie/anaconda3/envs/py37/lib/python3.7/site-packages/mergem/__init__.py", line 2, in <module>
    from .__merge_models import merge, translate
  File "/home/winnie/anaconda3/envs/py37/lib/python3.7/site-packages/mergem/__merge_models.py", line 280
    if (idx := alt_old_met_id.rfind('@')) > 0 or (idx := alt_old_met_id.rfind('_')) > 0:
            ^
SyntaxError: invalid syntax

**Comment by dnlobo** [comment]
Hello,

Unfortunately Python 3.7 does not support that syntax (:= was introduced in 3.8). Could you update your Python to a newer version?

Thanks.
